// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Direktorat Pengembangan Teknologi dan Sistem Informasi (DPTSI) - ITS",
            "url": "http://its.ac.id/dptsi",
            "email": "dptsi@its.ac.id"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "security": [
                    {
                        "CSRF Token": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication \u0026 Authorization"
                ],
                "summary": "Rute untuk mendapatkan link login melalui OpenID Connect",
                "responses": {
                    "200": {
                        "description": "Link login berhasil didapatkan",
                        "schema": {
                            "$ref": "#/definitions/responses.GeneralResponse"
                        }
                    },
                    "500": {
                        "description": "Terjadi kesalahan saat menghubungi provider OpenID Connect",
                        "schema": {
                            "$ref": "#/definitions/responses.GeneralResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "delete": {
                "security": [
                    {
                        "Session": []
                    },
                    {
                        "CSRF Token": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication \u0026 Authorization"
                ],
                "summary": "Rute untuk logout",
                "responses": {
                    "200": {
                        "description": "Logout berhasil",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.GeneralResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "data": {
                                            "type": "string"
                                        },
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/user": {
            "get": {
                "security": [
                    {
                        "Session": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication \u0026 Authorization"
                ],
                "summary": "Rute untuk mendapatkan data user yang sedang login",
                "responses": {
                    "200": {
                        "description": "Data user berhasil didapatkan",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.GeneralResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/responses.User"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "roles": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/responses.Role"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/csrf-cookie": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CSRF Protection"
                ],
                "summary": "Rute dummy untuk set CSRF-TOKEN cookie",
                "responses": {
                    "200": {
                        "description": "Cookie berhasil diset",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.GeneralResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/sdm": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SDM"
                ],
                "summary": "List semua SDM",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SDM"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SDM"
                ],
                "summary": "Tambah SDM",
                "parameters": [
                    {
                        "description": "Data SDM",
                        "name": "sdm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SDM"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.SDM"
                        }
                    }
                }
            }
        },
        "/sdm/{nik}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SDM"
                ],
                "summary": "Get SDM by NIK",
                "parameters": [
                    {
                        "type": "string",
                        "description": "NIK",
                        "name": "nik",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SDM"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SDM"
                ],
                "summary": "Update SDM by NIK",
                "parameters": [
                    {
                        "type": "string",
                        "description": "NIK",
                        "name": "nik",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data SDM",
                        "name": "sdm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SDM"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SDM"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SDM"
                ],
                "summary": "Hapus SDM by NIK",
                "parameters": [
                    {
                        "type": "string",
                        "description": "NIK",
                        "name": "nik",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/spesimen": {
            "post": {
                "description": "Membuat spesimen tanda tangan baru untuk SDM",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Spesimen"
                ],
                "summary": "Membuat spesimen tanda tangan baru",
                "parameters": [
                    {
                        "description": "Data spesimen",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateSpesimenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.SpesimenTandaTangan"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/spesimen/sdm/{idSdm}": {
            "get": {
                "description": "Mendapatkan spesimen tanda tangan berdasarkan ID SDM",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Spesimen"
                ],
                "summary": "Mendapatkan spesimen tanda tangan berdasarkan ID SDM",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID SDM",
                        "name": "idSdm",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SpesimenTandaTangan"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/spesimen/{id}": {
            "get": {
                "description": "Mendapatkan spesimen tanda tangan berdasarkan ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Spesimen"
                ],
                "summary": "Mendapatkan spesimen tanda tangan berdasarkan ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Spesimen",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SpesimenTandaTangan"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Memperbarui spesimen tanda tangan berdasarkan ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Spesimen"
                ],
                "summary": "Memperbarui spesimen tanda tangan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Spesimen",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data update spesimen",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateSpesimenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SpesimenTandaTangan"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Menghapus spesimen tanda tangan berdasarkan ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Spesimen"
                ],
                "summary": "Menghapus spesimen tanda tangan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Spesimen",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.SDM": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id_sdm": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.SpesimenTandaTangan": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id_sdm": {
                    "type": "string"
                },
                "id_spesimen": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updater": {
                    "type": "string"
                }
            }
        },
        "requests.CreateSpesimenRequest": {
            "type": "object",
            "required": [
                "data",
                "id_sdm"
            ],
            "properties": {
                "data": {
                    "type": "string"
                },
                "id_sdm": {
                    "type": "string"
                },
                "updater": {
                    "type": "string"
                }
            }
        },
        "requests.UpdateSpesimenRequest": {
            "type": "object",
            "required": [
                "data",
                "updater"
            ],
            "properties": {
                "data": {
                    "type": "string"
                },
                "updater": {
                    "type": "string"
                }
            }
        },
        "responses.GeneralResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 123
                },
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.Role": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "mahasiswa"
                },
                "name": {
                    "type": "string",
                    "example": "Mahasiswa"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "responses.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "5025201000@student.its.ac.id"
                },
                "name": {
                    "type": "string",
                    "example": "Mahasiswa ITS"
                },
                "picture": {
                    "type": "string",
                    "example": "https://my.its.ac.id/picture/00000000-0000-0000-0000-000000000000"
                },
                "preferred_username": {
                    "type": "string",
                    "example": "5025201000@student.its.ac.id"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.Role"
                    }
                },
                "sub": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                }
            }
        }
    },
    "securityDefinitions": {
        "CSRF Token": {
            "description": "CSRF token yang didapatkan dari browser -\u003e inspect element -\u003e application -\u003e storage -\u003e cookies -\u003e CSRF-TOKEN (Untuk firefox, storage berada pada tab tersendiri)",
            "type": "apiKey",
            "name": "x-csrf-token",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "Dokumentasi Base Project",
        "url": "http://localhost:8080/doc/project"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
