definitions:
  responses.GeneralResponse:
    properties:
      code:
        example: 123
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
  responses.Role:
    properties:
      id:
        example: mahasiswa
        type: string
      name:
        example: Mahasiswa
        type: string
      permissions:
        items:
          type: string
        type: array
    type: object
  responses.User:
    properties:
      email:
        example: 5025201000@student.its.ac.id
        type: string
      name:
        example: Mahasiswa ITS
        type: string
      picture:
        example: https://my.its.ac.id/picture/00000000-0000-0000-0000-000000000000
        type: string
      preferred_username:
        example: 5025201000@student.its.ac.id
        type: string
      roles:
        items:
          $ref: '#/definitions/responses.Role'
        type: array
      sub:
        example: 00000000-0000-0000-0000-000000000000
        type: string
    type: object
externalDocs:
  description: Dokumentasi Base Project
  url: http://localhost:8080/doc/project
info:
  contact:
    email: dptsi@its.ac.id
    name: Direktorat Pengembangan Teknologi dan Sistem Informasi (DPTSI) - ITS
    url: http://its.ac.id/dptsi
paths:
  /auth/login:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: Link login berhasil didapatkan
          schema:
            $ref: '#/definitions/responses.GeneralResponse'
        "500":
          description: Terjadi kesalahan saat menghubungi provider OpenID Connect
          schema:
            $ref: '#/definitions/responses.GeneralResponse'
      security:
      - CSRF Token: []
      summary: Rute untuk mendapatkan link login melalui OpenID Connect
      tags:
      - Authentication & Authorization
  /auth/logout:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: Logout berhasil
          schema:
            allOf:
            - $ref: '#/definitions/responses.GeneralResponse'
            - properties:
                code:
                  type: integer
                data:
                  type: string
                message:
                  type: string
              type: object
      security:
      - Session: []
      - CSRF Token: []
      summary: Rute untuk logout
      tags:
      - Authentication & Authorization
  /auth/user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Data user berhasil didapatkan
          schema:
            allOf:
            - $ref: '#/definitions/responses.GeneralResponse'
            - properties:
                code:
                  type: integer
                data:
                  allOf:
                  - $ref: '#/definitions/responses.User'
                  - properties:
                      roles:
                        items:
                          $ref: '#/definitions/responses.Role'
                        type: array
                    type: object
                message:
                  type: string
              type: object
      security:
      - Session: []
      summary: Rute untuk mendapatkan data user yang sedang login
      tags:
      - Authentication & Authorization
  /csrf-cookie:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Cookie berhasil diset
          schema:
            allOf:
            - $ref: '#/definitions/responses.GeneralResponse'
            - properties:
                code:
                  type: integer
                message:
                  type: string
              type: object
      summary: Rute dummy untuk set CSRF-TOKEN cookie
      tags:
      - CSRF Protection
securityDefinitions:
  CSRF Token:
    description: CSRF token yang didapatkan dari browser -> inspect element -> application
      -> storage -> cookies -> CSRF-TOKEN (Untuk firefox, storage berada pada tab
      tersendiri)
    in: header
    name: x-csrf-token
    type: apiKey
swagger: "2.0"
